# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-21 21:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_auto_20171119_1821'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='is_banner',
        ),
        migrations.AlterField(
            model_name='course',
            name='detail',
            field=models.TextField(verbose_name='\u8bfe\u7a0b\u8be6\u60c5'),
        ),
    ]
